# Site settings
title: Alex Chilton
description: Alex Chilton's portfolio â€” Senior Data / AI / Cloud Engineer with 20+ years experience across software engineering, data engineering, AI/ML and cloud architecture.
url: "https://alexchilton.github.io" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Alex Chilton
email: alex_chilton@gmx.co.uk

# Global settings
icon_size: 58

exclude: [vendor]

# Google Analytics tracking ID
google_analytics_tracking_id: